title: Coordinated Universal Time
email: apodcastfornow@gmail.com
description: A Podcast For Now
long_description:
>
 Coordinated Universal Time is a sonic collage of foxfire-side readings, thinking machines, disembodied conversations, music we found in this world or made in another. Deep time reverberations and field recordings from the front lines of a future held in common. An aural zine hand-pasted and neural-networked by solar golems from the 23rd century, still quickening in the coals of the present: a podcast for now.
baseurl: /
url: https://apodcastfornow.com
image_path: /assets/images/
permalink: pretty
sort_by: year, month
order: reverse
google_analytics: UA-22848601-4
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
feed:
  path: feed.xml
collections_dir: collections
collections:
  - episodes
jekyll_compose:
    auto_open: true