title: Coordinated Universal Time
email: apodcastfornow@gmail.com
description: A Podcast For Now
baseurl: /
url: https://apodcastfornow.com
image_path: /assets/images/
permalink: pretty
sort_by: year, month
order: reverse
google_analytics: UA-22848601-4
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
feed:
  path: feed.xml
collections_dir: collections
collections:
  - episodes
jekyll_compose:
    auto_open: true