title: Coordinated Universal Time
email: tyler@etters.co
description: A Podcast For Now
baseurl: /
url: https://utcpodcast.com
image_path: /assets/images/
permalink: pretty
sort_by: year, month
order: reverse
google_analytics: 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
feed:
  path: feed.xml
collections_dir: collections
collections:
jekyll_compose:
    auto_open: true